# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.1.0

# The set of tests to run to verify your module works correctly
tests:
  - name: First test case
    terraform_version: 1.5.7
    environment:
      TF_VAR_bacon: con
  - name: Second test
    terraform_version: 1.4.7
    environment:
      TF_VAR_bacon: acon