# The version of the configuration file format
version: 1
# Your module version - must be changed to release a new version
module_version: 0.2.0

stack_defaults:
  runner_image: non-existing-imagexxxxxx
  opentofu_version: "~> 1.7.0"
